import type { ExtractResponse, FeedbackRequest, PredictRequest, PredictionResponse, ReceiveRequest } from '../types/api'
const urls = { predict: import.meta.env.VITE_PREDICT_API_URL || 'http://155.248.254.195:6000', extract: import.meta.env.VITE_EXTRACT_API_URL || 'http://155.248.254.195:5000/extract', receive: import.meta.env.VITE_RECEIVE_API_URL || 'http://155.248.254.195:6000', feedback: import.meta.env.VITE_FEEDBACK_API_URL || 'http://155.248.254.195:5000' }
const useDevProxy = import.meta.env.DEV && import.meta.env.VITE_USE_API_PROXY !== 'false'
const endpoint = (url: string, path: string) => url.endsWith(path) ? url : `${url.replace(/\/$/, '')}${path}`
const endpoints = { predict: useDevProxy ? '/api/predict' : endpoint(urls.predict, '/predict'), extract: useDevProxy ? '/api/extract' : endpoint(urls.extract, '/extract'), receive: useDevProxy ? '/api/receive' : endpoint(urls.receive, '/receive'), feedback: useDevProxy ? '/api/feedback' : endpoint(urls.feedback, '/submit_feedback') }
async function post<T>(url: string, body: unknown): Promise<T> { const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 10000); try { const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body), signal: controller.signal }); if (!response.ok) throw new Error(`Request failed (${response.status}). Please check the API server and try again.`); try { return await response.json() as T } catch { throw new Error('The API returned an invalid response. Please check the API server.') } } catch (error) { if (import.meta.env.DEV) console.error(error); if (error instanceof DOMException && error.name === 'AbortError') throw new Error('The API took too long to respond. Please check that the API server is running and try again.'); if (error instanceof TypeError) throw new Error('Unable to connect to the API. Please check the API server and CORS configuration.'); throw error } finally { window.clearTimeout(timeout) } }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null }
function normalizePredictions(value: PredictionResponse): PredictionResponse { if (!isRecord(value) || !isRecord(value.predictions)) throw new Error('The prediction API returned an unexpected response.') ; return { predictions: Object.fromEntries(Object.entries(value.predictions).filter(([, score]) => typeof score === 'number')) } }
function normalizeRecommendations(value: ExtractResponse): ExtractResponse { if (!isRecord(value)) throw new Error('The recommendation API returned an unexpected response.'); const response = value as ExtractResponse & { suggested_medications?: ExtractResponse['medications']; suggested_pathology?: string[]; suggested_radiology?: string[]; suggested_pathology_test?: string[]; suggested_radiology_test?: string[] }; return { disease_name: typeof response.disease_name === 'string' ? response.disease_name : '', medications: Array.isArray(response.medications) ? response.medications : Array.isArray(response.suggested_medications) ? response.suggested_medications : [], pathology_tests: Array.isArray(response.pathology_tests) ? response.pathology_tests : Array.isArray(response.suggested_pathology) ? response.suggested_pathology : Array.isArray(response.suggested_pathology_test) ? response.suggested_pathology_test : [], radiology_tests: Array.isArray(response.radiology_tests) ? response.radiology_tests : Array.isArray(response.suggested_radiology) ? response.suggested_radiology : Array.isArray(response.suggested_radiology_test) ? response.suggested_radiology_test : [] } }
export const predictDisease = async (symptoms: string[]) => normalizePredictions(await post<PredictionResponse>(endpoints.predict, { symptoms } satisfies PredictRequest))
export const extractRecommendations = async (disease_name: string) => normalizeRecommendations(await post<ExtractResponse>(endpoints.extract, { disease_name }))
export const receiveDiagnosis = (symptoms: string[], final_diagnosis_by_doctor: string[]) => post(endpoints.receive, { symptoms, final_diagnosis_by_doctor } satisfies ReceiveRequest)
export const submitFeedback = (body: FeedbackRequest) => post(endpoints.feedback, body)